labourDepartmentAssam/grails-app/controllers/labourdepartmentassam/HomeController.groovy
package labourdepartmentassam

class HomeController {

    def index() { }
    def s
}

labourDepartmentAssam/grails-app/views/layouts/_footer.gsp
<footer id="footer" class="midnight-blue">

    <div class="container">
        <div id="row">
            <div class="col-sm-6">
                <ul class="pull-left">
                    <li><a href="#about"><i class="fa fa-empire fa-fw"></i>&nbsp;About Us</a></li>
                    <li><a href="#contact"><i class="fa fa-envelope fa-fw"></i>&nbsp;Contact Us</a></li>
                </ul>
                %{--</div>--}%
            </div>

            <div class="col-sm-6">
                <ul class="pull-right">
                    <li style="color: #ffffff">
                        <i class="fa fa-copyright fa-fw"></i> Damyant Software Pvt. Ltd.
                    </li>
                    <li class="twitter-follow">
                        <span class="fa-stack fa-fw">
                            <i class="fa fa-twitter fa-stack-2x"></i>
                        </span>

                    </li><!--//twitter-follow-->
                    <li class="twitter-tweet">
                        <span class="fa-stack fa-fw">
                            <i class="fa fa-facebook fa-stack-2x"></i>
                        </span>

                    </li>
                    <li class="facebook-like">
                        <span class="fa-stack fa-fw">
                            <i class="fa fa-skype fa-stack-2x"></i>
                        </span>
                    </li>
                    <li class="facebook-like">
                        <span class="fa-stack fa-fw">
                            <i class="fa fa-linkedin fa-stack-2x"></i>
                        </span>
                    </li>
                </ul>
            </div>
        </div>

    </div>
    %{--<div class="container text-center">--}%
    %{--<p class="text-muted">.</p>--}%
    %{--</div>--}%
</footer>

labourDepartmentAssam/grails-app/views/layouts/_leftNavBar.gsp
    <!-- Left column -->
    <a href="#"><strong><i class="glyphicon glyphicon-wrench"></i> Tools</strong></a>

    <hr>

    <ul class="list-unstyled">
        <li class="nav-header"> <a href="#" data-toggle="collapse" data-target="#userMenu">
            <h5>Settings <i class="glyphicon glyphicon-chevron-down"></i></h5>
        </a>
            <ul class="list-unstyled collapse in" id="userMenu">
                <li class="active"> <a href="#"><i class="glyphicon glyphicon-home"></i> Home</a></li>
                <li><a href="#"><i class="glyphicon glyphicon-envelope"></i> Messages <span class="badge badge-info">4</span></a></li>
                <li><a href="#"><i class="glyphicon glyphicon-cog"></i> Options</a></li>
                <li><a href="#"><i class="glyphicon glyphicon-comment"></i> Shoutbox</a></li>
                <li><a href="#"><i class="glyphicon glyphicon-user"></i> Staff List</a></li>
                <li><a href="#"><i class="glyphicon glyphicon-flag"></i> Transactions</a></li>
                <li><a href="#"><i class="glyphicon glyphicon-exclamation-sign"></i> Rules</a></li>
                <li><a href="#"><i class="glyphicon glyphicon-off"></i> Logout</a></li>
            </ul>
        </li>
        <li class="nav-header"> <a href="#" data-toggle="collapse" data-target="#menu2">
            <h5>Reports <i class="glyphicon glyphicon-chevron-right"></i></h5>
        </a>

            <ul class="list-unstyled collapse" id="menu2">
                <li><a href="#">Information &amp; Stats</a>
                </li>
                <li><a href="#">Views</a>
                </li>
                <li><a href="#">Requests</a>
                </li>
                <li><a href="#">Timetable</a>
                </li>
                <li><a href="#">Alerts</a>
                </li>
            </ul>
        </li>
        <li class="nav-header">
            <a href="#" data-toggle="collapse" data-target="#menu3">
                <h5>Social Media <i class="glyphicon glyphicon-chevron-right"></i></h5>
            </a>

            <ul class="list-unstyled collapse" id="menu3">
                <li><a href="#"><i class="glyphicon glyphicon-circle"></i> Facebook</a></li>
                <li><a href="#"><i class="glyphicon glyphicon-circle"></i> Twitter</a></li>
            </ul>
        </li>
    </ul>

    <hr>

    <a href="#"><strong><i class="glyphicon glyphicon-link"></i> Resources</strong></a>

    <hr>

    <ul class="nav nav-pills nav-stacked">
        <li class="nav-header"></li>
        <li><a href="#"><i class="glyphicon glyphicon-list"></i> Layouts &amp; Templates</a></li>
        <li><a href="#"><i class="glyphicon glyphicon-briefcase"></i> Toolbox</a></li>
        <li><a href="#"><i class="glyphicon glyphicon-link"></i> Widgets</a></li>
        <li><a href="#"><i class="glyphicon glyphicon-list-alt"></i> Reports</a></li>
        <li><a href="#"><i class="glyphicon glyphicon-book"></i> Pages</a></li>
        <li><a href="#"><i class="glyphicon glyphicon-star"></i> Social Media</a></li>
    </ul>

    <hr>
    <ul class="nav nav-stacked">
        <li class="active"><a href="http://bootply.com" title="The Bootstrap Playground" target="ext">Playground</a></li>
        <li><a href="/tagged/bootstrap-3">Bootstrap 3</a></li>
        <li><a href="/61518" title="Bootstrap 3 Panel">Panels</a></li>
        <li><a href="/61521" title="Bootstrap 3 Icons">Glyphicons</a></li>
        <li><a href="/62603">Layout</a></li>
    </ul>

    <hr>

    <a href="#"><strong>Want More Templates?</strong></a>

    <hr>

    <ul class="nav nav-stacked">
        <li class="active"><a rel="nofollow" href="http://goo.gl/pQoXEh" target="ext">Premium Themes</a></li>
        <li><a rel="nofollow" href="http://gridgum.com/themes/category/bootstrap-themes/?affiliates=45">GridGum</a></li>
        <li><a rel="nofollow" href="http://bootstrapzero.com">BootstrapZero</a></li>
    </ul>
















    %{--<style>--}%
    %{--#ajaxLogin {--}%
        %{--background-color: #EEEEFF;--}%
        %{--display: none;--}%
    %{--}--}%
    %{--#ajaxLogin .inner {--}%
        %{--width: 260px;--}%
        %{--margin:0px auto;--}%
        %{--text-align:left;--}%
        %{--padding:10px;--}%
        %{--border-top:1px dashed #499ede;--}%
        %{--border-bottom:1px dashed #499ede;--}%
        %{--background-color:#EEF;--}%
    %{--}--}%
    %{--#ajaxLogin .inner .fheader {--}%
        %{--padding:4px;margin:3px 0px 3px 0;color:#2e3741;font-size:14px;font-weight:bold;--}%
    %{--}--}%
    %{--#ajaxLogin .inner .cssform p {--}%
        %{--clear: left;--}%
        %{--margin: 0;--}%
        %{--padding: 5px 0 8px 0;--}%
        %{--padding-left: 105px;--}%
        %{--border-top: 1px dashed gray;--}%
        %{--margin-bottom: 10px;--}%
        %{--height: 1%;--}%
    %{--}--}%
    %{--#ajaxLogin .inner .cssform input[type='text'] {--}%
        %{--width: 120px;--}%
    %{--}--}%
    %{--#ajaxLogin .inner .cssform label{--}%
        %{--font-weight: bold;--}%
        %{--float: left;--}%
        %{--margin-left: -105px;--}%
        %{--width: 100px;--}%
    %{--}--}%
    %{--#ajaxLogin .inner .login_message {color:red;}--}%
    %{--#ajaxLogin .inner .text_ {width:120px;}--}%
    %{--#ajaxLogin .inner .chk {height:12px;}--}%
    %{--.errorMessage { color: red; }--}%
    %{--</style>--}%
    %{--<div id='ajaxLogin' class="jqmWindow" style="z-index: 3000;">--}%
        %{--<div class='inner'>--}%
            %{--<div class='fheader'>Please Login..</div>--}%
            %{--<form action='${request.contextPath}/j_spring_security_check' method='POST'--}%
                  %{--id='ajaxLoginForm' name='ajaxLoginForm' class='cssform'>--}%
                %{--<p>--}%
                    %{--<label for='username'>Login ID</label>--}%
                    %{--<input type='text' class='text_' name='j_username' id='username' />--}%
                %{--</p>--}%
                %{--<p>--}%
                    %{--<label for='password'>Password</label>--}%
                    %{--<input type='password' class='text_' name='j_password' id='password' />--}%
                %{--</p>--}%
                %{--<p>--}%
                    %{--<label for='remember_me'>Remember me</label>--}%
                    %{--<input type='checkbox' class='chk' id='remember_me'--}%
                           %{--name='_spring_security_remember_me'/>--}%
                %{--</p>--}%
                %{--<p>--}%
                    %{--<span class="button" id="authAjax">Login</span>--}%
                    %{--<span class="button" id="cancelLogin">Cancel</span>--}%
                %{--</p>--}%
            %{--</form>--}%
            %{--<div style='display: none; text-align: left;' id='loginMessage'></div>--}%
        %{--</div>--}%
    %{--</div>--}%

    %{--<script type='text/javascript'>--}%
        %{--var onLogin;--}%
        %{--$.ajaxSetup({--}%
            %{--beforeSend : function(xhr, event) {--}%
                %{--// save the 'success' function for later use--}%
                %{--onLogin = event.success;--}%
            %{--},--}%
            %{--statusCode: {--}%
                %{--// Set up a global AJAX error handler to handle the 401--}%
                %{--// unauthorized responses. If a 401 status code comes back,--}%
                %{--// the user is no longer logged-into the system and can not--}%
                %{--// use it properly.--}%
                %{--401: function() {--}%
                    %{--showLogin();--}%
                %{--}--}%
            %{--}--}%
        %{--});--}%

        %{--function showLogin() {--}%
            %{--var ajaxLogin = $('#ajaxLogin');--}%
            %{--ajaxLogin.css('text-align','center');--}%
            %{--// use jqModal to show and align login panel--}%
            %{--ajaxLogin.jqmShow();--}%
        %{--}--}%

        %{--function cancelLogin() {--}%
            %{--$('#ajaxLogin').jqmHide();--}%
        %{--}--}%

        %{--function authAjax() {--}%
            %{--$('#loginMessage').html('Sending request ...').show();--}%

            %{--var form = $('#ajaxLoginForm');--}%
            %{--var config = {--}%
                %{--type : 'post'--}%
                %{--,url : form.attr('action')--}%
                %{--,data : form.serialize()--}%
                %{--,async : false--}%
                %{--,dataType : 'JSON'--}%
                %{--,success: function(response) {--}%
                    %{--form[0].reset();--}%
                    %{--$('#loginMessage').empty();--}%
                    %{--$('#ajaxLogin').jqmHide();--}%
                    %{--if (onLogin) {--}%
                        %{--// execute the saved event.success function--}%
                        %{--onLogin(response);--}%
                    %{--}--}%
                %{--}--}%
                %{--,error : function (response) {--}%
                    %{--var responseText = response.responseText || '[]';--}%
                    %{--var json = responseText.evalJSON();--}%
                    %{--if (json.error) {--}%
                        %{--$('#loginMessage').html("<span class='errorMessage'>" + json.error + '</error>');--}%
                    %{--} else {--}%
                        %{--$('#loginMessage').html(responseText);--}%
                    %{--}--}%
                %{--}--}%
                %{--,beforeSend : function(xhr, event) {--}%
                    %{--//console.log("overriding default behaviour");--}%
                %{--}--}%
            %{--}--}%
            %{--$.ajax(config);--}%
        %{--}--}%

        %{--$(function() {--}%
            %{--$('#ajaxLogin').jqm({modal: true, trigger: 'span.jqmTrigger'});--}%
            %{--$('#authAjax').click(authAjax);--}%
            %{--$('#cancelLogin').click(cancelLogin);--}%
        %{--});--}%
    %{--</script>--}%

labourDepartmentAssam/grails-app/views/layouts/_topNavBar.gsp
<div class="container topImageHeader">
    <g:img dir="images" file="labour1.jpg" style="width: 100%;margin: 5px auto; border-radius: 6px;"/>
</div>

<div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        %{--<a class="navbar-brand" href="#" style=" padding: 1px;margin-right: 10px;vertical-align: bottom;"><img src="${resource(dir: 'images', file: 'symphonie11.png')}" alt="insuranceApp" style="height: 70%; margin-top: 7%;"/></a>--}%
    </div>

    <div id="navbar" class="navbar-collapse collapse navbar-other">

        <ul class="nav navbar-nav">

            <li><g:link controller="home" action="index"><i class="fa fa-home fa-fw"></i>Home</g:link></li>
            <sec:ifLoggedIn>
                <li><g:link controller="employeeQRGenerate" action="qrUpdate"><i
                        class="glyphicon glyphicon-user fa-fw"></i>Worker Registration</g:link></li>
                <li><g:link controller="employeeQRGenerate" action="studentQRList"><i
                        class="glyphicon glyphicon-user fa-fw"></i>Worker List</g:link></li>
                <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle"><i
                        class="glyphicon glyphicon-stats fa-fw"></i>Analytics<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><g:link controller="employeeQRGenerate" action="report">Graphical Analytics</g:link></li>
                    <li><g:link controller="employeeQRGenerate" action="schemeWiseReport">Scheme Wise Financial Details</g:link></li>
                    <li><g:link controller="employeeQRGenerate" action="districtWiseReport">District Wise Financial Details</g:link></li>
                </ul></li>
            </sec:ifLoggedIn>
        </ul>

        <sec:ifLoggedIn>
            <ul class="nav navbar-nav navbar-right">
                <sec:ifAnyGranted roles="ROLE_ADMIN">
                    <li><a href="#"><i class="fa fa-user-md fa-fw"></i> Manage</a>
                    </li>
                </sec:ifAnyGranted>
                <li><g:link controller="logout">
                    <i class="fa fa-sign-out fa-fw"></i>
                    </span>Logout</g:link></li>
            </ul>
        </sec:ifLoggedIn>
        <sec:ifNotLoggedIn>
            <ul class="nav navbar-nav navbar-right">
                <li><g:link controller="signUp" action="signUp"><i class="fa fa-pencil fa-fw"></i>Sign up</g:link></li>
                <li><g:link controller="login" action="auth">
                    <i class="fa fa-sign-in fa-fw"></i>

                    Sign in
                </g:link></li>
            </ul>
        </sec:ifNotLoggedIn>
    </div>
</div>

labourDepartmentAssam/grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Labour and Employment Department, Assam </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="${resource(dir: 'images', file: 'govtofAssam.png')}" type="image/x-icon">
    <link rel="apple-touch-icon" href="${resource(dir: 'images', file: 'govtofAssam.png')}">
    <link rel="apple-touch-icon" sizes="114x114" href="${resource(dir: 'images', file: 'govtofAssam.png')}">
    <link rel="stylesheet" href="${resource(dir: 'css', file: 'bootstrap.min.css')}" type="text/css">
    <link rel="stylesheet" href="${resource(dir: 'css/font-awesome-4.3.0/css', file: 'font-awesome.min.css')}" type="text/css">
    <link rel="stylesheet" href="${resource(dir: 'css', file: 'main.css')}" type="text/css">
    <script type='text/javascript' charset='utf-8' src='${resource(dir: 'js', file: 'base.js')}'></script>
    <script type='text/javascript' charset='utf-8' src='${resource(dir: 'js', file: 'jquery.js')}'></script>
    <script type='text/javascript' charset='utf-8' src='${resource(dir: 'js', file: 'main.js')}'></script>
    <script type='text/javascript' charset='utf-8' src='${resource(dir: 'js', file: 'bootstrap.min.js')}'></script>
    <g:layoutHead/>
    <g:javascript library="application"/>
    <r:layoutResources/>
</head>

<body>
<nav class="navbar navbar-inverse navbar-default hrLine">
    <g:render template="/layouts/topNavBar"/>
</nav>
<div class=" mainContent container" style="min-height: 383px;">
        <g:layoutBody/>
</div>
<r:layoutResources/>
<g:render template="/layouts/footer"/>
</body>
</html>